### ISSUE TITLE
[FEATURE-REQUEST] events for toggling muted/mic/camera

### ISSUE THREAD

**Issue by AdrianMrn** [daily-co/daily-js#168]
# Feature request

I expected the `started-camera` event to fire every time I enabled my camera after turning it off, but it only fires the first time I enable the camera (or if it is automatically enabled when the call starts).

I'd also like to be able to track other events, like whether the participant has muted the meeting, and whether they've turned their mic on or off.

# Why you need this

We'd like to send these events to our server to keep track of the viewers' states and display them to our admins in a dashboard.

# Alternatives you've considered

Right now, I'm polling the callFrame's state every couple of seconds to check whether these values are enabled or disabled.

# Additional context

If you're open to PRs, I'll look into this and do the work myself and create a PR for you to review.

**Comment by Regaddi** [comment]
Hey @AdrianMrn,

we already emit a [`participant-updated`](https://docs.daily.co/reference#participant-updated) event, whenever a participant's state changes. It doesn't fire only when a user toggles their cam or mic: it is also emitted when a participants starts or stops a screen share or recording, or other information changes, like their name or role inside the meeting.
This means you'll have to do a small comparison to a previous state in order to detect cam/mic toggles.

Here is some simplified example code illustrating the use case:

```javascript
let isCamEnabled = true;

const handleParticipantUpdated = ({ participant }) => {
  if (participant.video !== isCamEnabled) {
    // Cam was toggled: update internal state & track event
    isCamEnabled = participant.video;
    trackCamToggle(isCamEnabled);
  }
}

daily.on('participant-updated', handleParticipantUpdated);
```

Microphone toggles would work similarly using `participant.audio`.

The `started-camera` event is only triggered during the loading sequence of a call and is meant to inform about the user's camera being accessed from now on (after `getUserMedia()`).

Please let us know in case this doesn't help you solve the problem your facing.

**Comment by AdrianMrn** [comment]
This solves my issue perfectly, thanks so much for the fast response!
