### ISSUE TITLE
Knock Event?

### ISSUE THREAD

**Issue by PorterK** [daily-co/daily-js#20]
Hi, is there a way to detect that a knock has occurred? 

We want to display some custom overlay over the video if a participant has left the call, but close that when someone new tries to join via knocking.

Any way to achieve this with the current API? As far as I can tell, no events are making through while in the "requesting" state

**Comment by mattieruth** [comment]
Apologies this was never addressed. I don't expect an answer now but it's unclear from reading this if the request is for the person knocking to get events about participants in the room joining and leaving or for people in the room to get events about people knocking.

If the former, then our API does not support anyone who has not been authorized in the meeting to obtain details about participants in the meeting for security reasons.  If the latter, then there should be sufficient events provided only to the owners in the meeting. All owners should receive the [`waiting-participant-added`](https://docs.daily.co/reference/daily-js/events/participant-events#waiting-participant-added) when someone knocks (or if they join a room and someone is already knocking), the [`waiting-participant-updated`](https://docs.daily.co/reference/daily-js/events/participant-events#waiting-participant-updated) event if a knocking participant changes their name, and a [`waiting-participant-left`](https://docs.daily.co/reference/daily-js/events/participant-events#waiting-participant-removed) event if a knocking participant leaves.

Closing because this has been dormant for so long, but feel free to re-open.
