### ISSUE TITLE
Prebuilt creates two iframes

### ISSUE THREAD

**Issue by ahkhanjani** [daily-co/daily-js#205]
Here's the code I use for the call:

```javascript
import React, { useCallback, useEffect, useRef } from 'react';
import DailyIframe, {
  type DailyCall,
  type DailyCallOptions,
} from '@daily-co/daily-js';

const CALL_OPTIONS: DailyCallOptions = {
  showLeaveButton: true,
  iframeStyle: {
    top: '0',
    left: '0',
    width: '100%',
    aspectRatio: '16 / 9',
    border: '0',
    borderRadius: '12px',
  },
};

const Call: React.FC<{
  room: string;
  setRoom: React.Dispatch<React.SetStateAction<string | null>>;
  callFrame: DailyCall | null;
  setCallFrame: React.Dispatch<React.SetStateAction<DailyCall | null>>;
}> = ({ room, setRoom, callFrame, setCallFrame}) => {
  const callRef = useRef<HTMLDivElement>(null);

  const createAndJoinCall = useCallback(() => {
    const newCallFrame = DailyIframe.createFrame(
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-ignore
      callRef?.current,
      CALL_OPTIONS
    );

    setCallFrame(newCallFrame);

    newCallFrame.join({ url: room });

    const leaveCall = () => {
      setRoom(null);
      setCallFrame(null);
      callFrame?.destroy();
    };

    newCallFrame.on('left-meeting', leaveCall);
  }, [callFrame, room, setCallFrame, setRoom]);

  useEffect(() => {
    if (callFrame) return;

    createAndJoinCall();
  }, [callFrame, createAndJoinCall]);

  return (
     <div className="w-full">
       <div ref={callRef} />
     </div>
  );
};
export default Call;
```

And here's the result:

![ss](https://user-images.githubusercontent.com/72540492/209977874-397bc11a-07fa-4a45-8850-553e73c99ad4.png)

So it basically creates two identical call windows and you can interact with them separately. Any idea why this is happening?

Here's the specs:
- React and React Dom v18.2.0
- Nextjs v13.1.1
- Chrome v108

**Comment by Regaddi** [comment]
Hey @ahkhanjani,

thanks for your report and for providing the code.
I have a hunch that the `useEffect` calling `createAndJoinCall` is called twice in dev mode, which might result in 2 calls to `createFrame`.

Also `createAndJoinCall` has a dependency on `callFrame`, which is probably unnecessary: you should be able to call `newCallFrame.destroy()`, which should avoid `createAndJoinCall` from being re-created when `callFrame` changes (this might not fix the issue, but is just something I noticed while reading the code).

In summary I think you see 2 iframe instances, because your code says so 😅
Another idea might be to add a DOM check in your `useEffect`, like

```ts
  useEffect(() => {
    if (callFrame) return;
    const iframe = callRef.current?.querySelector('iframe');
    if (iframe) return;

    createAndJoinCall();
  }, [callFrame, createAndJoinCall]);
```

I'm still quite certain the underlying issue is a wonky state-dependency though, so see this as kind of a last resort solution.

Let me know if you're still seeing issues!

Cheers,
Christian

**Comment by ahkhanjani** [comment]
@Regaddi Thank you for your reply. I suspected that the dev mode might be the issue but since I followed one of the example repos by Daily, I kind of decided to trust the code.

> Also `createAndJoinCall` has a dependency on `callFrame`, which is probably unnecessary: you should be able to call `newCallFrame.destroy()`, which should avoid `createAndJoinCall` from being re-created when `callFrame` changes (this might not fix the issue, but is just something I noticed while reading the code).

Thank you for this tip. I really couldn't think of it.



> Another idea might be to add a DOM check in your `useEffect`, like
> 
> ```ts
>   useEffect(() => {
>     if (callFrame) return;
>     const iframe = callRef.current?.querySelector('iframe');
>     if (iframe) return;
> 
>     createAndJoinCall();
>   }, [callFrame, createAndJoinCall]);
> ```

This solves the issue. createAndJoinCall() was being called twice before. Thank you so much for the solution!
