### ISSUE TITLE
Not getting participants audio

### ISSUE THREAD

**Issue by Harsh4999** [daily-co/daily-js#225]
So I am using Daily js to on client side where user click join button and they join the room with these config:

```js
        const call = DailyIframe.createCallObject({
            url: "ROOM URL",
            videoSource: false,
            audioSource: true,
            subscribeToTracksAutomatically: true
        });       
        await call.join();
```

Now the problem is that when someone speaks in the room I am not getting any audio on client side on speaker. What can be the reason for this?

**Comment by mattieruth** [comment]
Hi! Thanks for the report. I have tried to reproduce this on a default room and have not had luck. Can you provide more specifics about your room settings and how your application attaches the audio tracks to elements?

[Here is the gist](https://github.com/mattieruth/daily-gists-by-ruthless/blob/main/basic-call-object.html) I use for testing in case that helps.

**Comment by Harsh4999** [comment]
@mattieruth 
Okay so I was able to resolve this but now I am encountering another issue that is in 1 window it is not allowing me to operate 2 daily.co iframe instance I want to do so because I want to let user join meet but also in meet I want a bot to join which will be injected by a component do you know any work around to this or in general how do you inject a virtual participant in Daily.co meet? The idea is that bot will be able to interact with user I wanted to do everything in same tab but it seems it wont allow me to make 2 DailyFrame instances in same window

**Comment by mattieruth** [comment]
Hi! Glad you figured it out. As for multiple call instances. It is true, we do not allow multiple on the same window because we currently rely on the window and having multiple cause a multitude of bugs, [as the docs suggest](https://docs.daily.co/reference/daily-js/factory-methods/create-call-object).  The only way to get around this is if you put your call objects in separate iframes, so that they don't share the window.

For future questions like this, I suggest joining [our community](https://community.daily.co/) where you'll find better support.

Thanks!
