### ISSUE TITLE
[FEATURE-REQUEST] Unknown parameter `dtx` in `screenVideo` settings.

### ISSUE THREAD

**Issue by mklepaczewski** [daily-co/daily-js#243]
# Feature request

Explain the meaning of the `dtx` parameter in documentation. 

`dtx` is returned in calls to `getSendSettings()`:
```js
console.log(call.getSendSettings()?.screenVideo);
{dtx: true, maxBitrate: 2000000, scaleResolutionDownBy: 1, maxFramerate: 30}
```

# Why you need this

I need to know the details of my app and how it works.

# Alternatives you've considered

Ignorance, but it hasn't worked out for me in the past.

**Comment by mattieruth** [comment]
Thanks for the question! You've highlighted a field that actually doesn't need to be there and is only there because of historical reasons. [Here's a link](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpSender/setParameters#dtx) to what that field refers to, which, as you can see is only used for `audio` tracks and therefore ignored for `screenVideo`.

Guess in this case, your alternative would've worked out just fine 😂 

Meanwhile, I'm making a ticket to remove that field.
