### ISSUE TITLE
Cross-Site Scripting vulnerability in dependency of version 0.9.991

### ISSUE THREAD

**Issue by nickpell** [daily-co/daily-js#48]
Running ```npm audit``` with version 0.9.991 installed yields the following warning: 

 Moderate       Cross-Site Scripting                                         
 Package        serialize-javascript                                         
 Patched in     >=2.1.1                                                      
 Dependency of  @daily-co/daily-js                                           
 Path           @daily-co/daily-js > rollup-plugin-terser > serialize-javascript                                        
 More info      https://npmjs.com/advisories/1426

**Comment by kwindla** [comment]
Hi,

Thank you for reporting this.

It's fixed here: https://github.com/daily-co/daily-js/pull/49

We will push a new beta version shortly. Please note that this was not a dependency in production, because `rollup-plugin-terser` was never part of the build (it was mistakenly included in the `dependencies`, rather than the `devDependencies`, section of `package.json`.

Yours,
Kwin
