### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by hueter** [daily-co/daily-js#52]
Hello 👋 

My team is using this package in a TypeScript codebase. I am wondering if you had any interest in adding TypeScript declarations to this repo? This would just be a type declarations file `index.d.ts` that ships with the npm package but doesn't affect the build otherwise. I'm happy to get started on that if you're interested. Alternatively, I can submit type definitions to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) as a separate package.

Thoughts?

**Comment by kompfner** [comment]
Hi! Thanks for reaching out. Yes, as a matter of fact, we're really interested in being TypeScript-friendly! We've actually started using TypeScript ourselves for some stuff we're currently cooking up, which required adding a few types to `daily-js` already.

We weren’t planning on pushing these types into `master` quite yet since the declaration file is still totally a work in progress and a long ways from having reasonable coverage of the `daily-js` API. But I’d hate for you to be blocked! So I went ahead and pushed up a `with-types` branch which includes the crude `index.d.ts` we’ve been using so far. More than happy to collaborate with you on this and take PRs into this branch, if you'd like :) Then when the file has good enough coverage, we can merge it into `master`.

Is this helpful at all? Does this workflow make sense for you and your team?

**Comment by hueter** [comment]
Sounds great! I will definitely check out that branch and happy to collaborate / make PRs against it. Currently we're not technically blocked but we aren't type safe either since we're just declaring everything as `any`, but I have a feeling pulling in the types from that branch will help a lot and start us down a path of adding to it.

**Comment by kompfner** [comment]
Update: types now live in the `master` branch, in https://github.com/daily-co/daily-js/blob/master/wip-index.d.ts. They should be complete, but they haven't been published quite yet (`package.json` needs to point to them and another version of `daily-js` has to be published to npm first). Feel free to use them, though, and don't hesitate to let us know if you run into any issues!

**Comment by hueter** [comment]
hi @kompfner thanks for publishing the TypeScript definitions in the latest version! 

A couple of updates:

1.  I made a PR #81 for suggested changes from my end based on my observations
2. Some of the fields are snake_case in the type definitions but camelCase in the official docs. Notably `joined_at`

**Comment by dbanisimov** [comment]
A few other missing/wrong pieces:

1. `setOutputDevice` instance method accepts an object `{ outputDeviceId }`, but type declarations has the parameter as `audioDevice: { id?: string }`
2. `screenAudioTrack` property is missing on the `DailyParticipant` interface
3. `load` instance method doesn't have any parameters, but type declaration has non-optional `properties: DailyLoadOptions`

**Comment by kompfner** [comment]
> A few other missing/wrong pieces:
> 
> 1. `setOutputDevice` instance method accepts an object `{ outputDeviceId }`, but type declarations has the parameter as `audioDevice: { id?: string }`
> 2. `screenAudioTrack` property is missing on the `DailyParticipant` interface
> 3. `load` instance method doesn't have any parameters, but type declaration has non-optional `properties: DailyLoadOptions`

Thanks very much @dbanisimov! Good catches. Opening a PR soon with the fixes. Re: point 3—technically `load` can take an argument, but you're totally right that it's not at all required, and in our documentation we hide that fact and discourage its use.

**Comment by rememberlenny** [comment]
I had strongly considered both Daily and Twilio, and ended up being more attracted to Twilio due to their Typescript native tutorials.

**Comment by kompfner** [comment]
@rememberlenny, I appreciate your letting us know why you made that choice! Helps to know what we could do better to help folks like you use Daily successfully. (Btw, if you don't mind, would love to know what docs you were using that you wished were in TS).

Not to be pushy (I'm engineering, not sales, I promise), but juuuust in case part of your decision was based on wondering "does Daily care really care about TypeScript? this issue's been open a while...": we actually use daily-js as a TS library _extensively_ ourselves! Our [Prebuilt](https://docs.daily.co/guides/products/prebuilt#main) is made with TS, as is our new [daily-react-hooks](https://github.com/daily-co/daily-react-hooks) library and our [react-native-daily-js](https://github.com/daily-co/react-native-daily-js) library and [its demo](https://github.com/daily-co/react-native-daily-js-playground).

OK, I'm done 😛 . Best of luck!

**Comment by rememberlenny** [comment]
Well I didn’t know about the daily hooks library. The main reason was because the react practices in the examples were antiquated and didn’t see to be written with actual use cases in mind, and the react call object examples were written using prop types, instead of typescript.

As an eng focused product? This gave me a lot of doubt about the rate at which Daily, was actually serving its core user base.

The docs are also quite horrendous when it comes to solving basic problems and navigating the examples and poor docs created the sense that there was so much behind the scenes being managed, that the actual end user experience was myopically focused on toy examples.

**Comment by rememberlenny** [comment]
Thank you. The product itself is wonderful.
