### ISSUE TITLE
Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to parse SessionDescription. Invalid value: Infinity.

### ISSUE THREAD

**Issue by justinfaulkner** [daily-co/daily-js#62]
![daily-setRemoteDescription-error](https://user-images.githubusercontent.com/49652/83701785-9e379200-a5bf-11ea-99d2-5768ffc43eb4.png)

I ran into this issue in testing. React app (based off daily-demos/react-demo), using `callObject`, Windows, Chrome 83.0.4103.61. My test involved about 7 participants  moving between about 5 Daily rooms. Only one of the clients encountered this error, and the rest continued to work.

I'm using `"@daily-co/daily-js": "0.9.992-beta.4",`

Is this error preventable somehow?

**Comment by kwindla** [comment]
Thanks for supplying to console log. That looks like a timing bug. The remote client info object is empty in the log line that starts "not unified plan". That shouldn't ever happen, and probably is only possible if there was an unusual leave/join timing issue.

We will put a guard around this code so that there's no error in this cases and we just back out of the attempt to connect and gracefully try to connect again.

**Comment by kwindla** [comment]
Hi, this is fixed now. We very much appreciate the bug report.
